# -- DEV DOCKER-COMPOSE --
# -- DO NOT USE IN PRODUCTION! --

services:
  db:
    container_name: wiki-db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
    logging:
      driver: "none"
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  adminer:
    container_name: wiki-adminer
    image: adminer:latest
    logging:
      driver: "none"
    ports:
      - "3001:8080"

  # solr:
  #   container_name: wiki-solr
  #   image: solr:7-alpine
  #   logging:
  #     driver: "none"
  #   ports:
  #     - "8983:8983"
  #   volumes:
  #     - solr-data:/opt/solr/server/solr/mycores
  #   entrypoint:
  #     - docker-entrypoint.sh
  #     - solr-precreate
  #     - wiki

  wiki:
    container_name: wiki-app
    build:
      context: ../..
      dockerfile: dev/containers/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
#    uncomment the lines above if you don't use the proxy in https://github.com/LuisMeirelles/proxy
#    ports:
#      - "3000:3000"
    labels:
        traefik.enable: "true"
        traefik.http.routers.wiki.entrypoints: "websecure"
        traefik.http.routers.wiki.rule: "Host(`${APP_URL}`)"
        traefik.http.services.wiki.loadbalancer.server.port: 3000
        traefik.http.routers.wiki.tls: "true"
    networks:
        - proxy
        - default
    volumes:
      - ../..:/wiki
      - ../../node_modules:/wiki/node_modules
      - /wiki/.git
    command: ["yarn", 'dev']

volumes:
  db-data:
  # solr-data:

networks:
    proxy:
        external: true

